
version: "2"

services:
    weewx:
        image: tweed15pip:latest
        container_name: tumbleweed
        restart: unless-stopped
        volumes:
        - ./tmpdata/archive:/home/weewx/weewx-data/archive
        - ./tmpdata/html:/home/weewx/weewx-data/public_html

    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginxtumbleweed
        restart: unless-stopped
        ports:
        - "9201:80"
        volumes:
        - ./tmpdata/html:/usr/share/nginx/html

