#------------------------------------------------------------
# to build:
#    docker compose build [imagename]
#
# to test:
#    docker compose up test
#    docker compose down
#
# to run:
#    docker compose up weewx nginx [-d]
#
# to stop/delete containers started via docker compose
#    docker compose down
#
# note:
#   this creates a 'tmpdata' subdir in the local directory
#   for shared storage. This needs to be clean up manually
#   which might require sudo (linux)
#
# alternate quicktest incantation using docker:
#   docker run --rm -it rocky8-v4-pkg:test
#
# interactively running the 'run' image will not print
# LOOP to stdout because StdPrint is removed in the image
# creation process which is for more typical testing.
#------------------------------------------------------------

version: "3.8"

services:
    test:
        image: rocky8-v4-pkg:test
        build:
            context: ./
            target: test
        volumes:
          - ./tests:/home/weetest/tests
    run:
        image: rocky8-v4-pkg:run
        build:
            context: ./
            target: run

    weewx:
        image: rocky8-v4-pkg:run
        container_name: rocky8-v4-pkg
        restart: unless-stopped
        volumes:
          - ./tmpdata/archive:/home/weewx/weewx-data/archive
          - ./tmpdata/html:/home/weewx/weewx-data/public_html

    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginxrocky8-v4-pkg
        restart: unless-stopped
        ports:
          - "8811:80"
        volumes:
          - ./tmpdata/html:/usr/share/nginx/html:ro

