#------------------------------------------------------------
# to build:
#    docker compose build [imagename]
#
# to test:
#    docker compose up test
#    docker compose down
#
# to run:
#    docker compose up weewx nginx [-d]
#
# to stop/delete containers started via docker compose
#    docker compose down
#
# note:
#   this creates a 'tmpdata' subdir in the local directory
#   for shared storage. This needs to be clean up manually
#   which might require sudo (linux)
#
# alternate quicktest incantation using docker:
#   docker run --rm -it rocky8-v5-pip:test
#
# interactively running the 'run' image will not print
# LOOP to stdout because StdPrint is removed in the image
# creation process which is for more typical testing.
#------------------------------------------------------------

version: "3.8"

services:

    base:
        image: rocky8:base
        build:
            context: ./
            target: base

    v5-pip:
        image: rocky8:v5-pip
        build:
            context: ./
            target: v5pip

    v4-pkg:
        image: rocky8:v4-pkg
        build:
            context: ./
            target: v4pkg

    v4-setup:
        image: rocky8:v4-setup
        build:
            context: ./
            target: v4setup

    weewx-v5pip:
        image: rocky8:v5-pip
        container_name: rocky8-v5pip
        restart: unless-stopped
        volumes:
          - ./tmpdata/archive:/home/weewx/weewx-data/archive
          - ./tmpdata/html:/home/weewx/weewx-data/public_html

    nginx-v5pip:
        image: nginx:1.18.0-alpine
        container_name: nginxrocky8-v5pip
        restart: unless-stopped
        ports:
          - "8801:80"
        volumes:
          - ./tmpdata/html:/usr/share/nginx/html:ro

