
version: "2"

services:
    weewx:
        image: leap15pip:latest
        container_name: leap
        restart: unless-stopped
        volumes:
        - ./tmpdata/archive:/home/weewx/weewx-data/archive
        - ./tmpdata/html:/home/weewx/weewx-data/public_html

    nginx:
        image: nginx:1.18.0-alpine
        container_name: nginxleap
        restart: unless-stopped
        ports:
        - "9101:80"
        volumes:
        - ./tmpdata/html:/usr/share/nginx/html:ro

